#include <header.h>

uint8_t keycodes[][6] = {
    {HID_KEY_ESCAPE},
    {HID_KEY_CONTROL_LEFT, HID_KEY_X},
    {HID_KEY_CONTROL_LEFT, HID_KEY_C},
    {HID_KEY_CONTROL_LEFT, HID_KEY_F5},
    {HID_KEY_SHIFT_LEFT, HID_KEY_GUI_LEFT, HID_KEY_S},
    {HID_KEY_CONTROL_LEFT, HID_KEY_V},
    {HID_KEY_GUI_LEFT, HID_KEY_H},
    {HID_KEY_MENU},
    {HID_KEY_SHIFT_LEFT, HID_KEY_S, HID_KEY_U, HID_KEY_S, HID_KEY_S, HID_KEY_Y},
    {HID_KEY_SCROLL_LOCK},
    {HID_KEY_L},
    {0x18},
    {HID_KEY_SHIFT_LEFT, HID_KEY_1},
    {HID_KEY_G, HID_KEY_R, HID_KEY_E, HID_KEY_A, HID_KEY_T},
    {HID_KEY_CONTROL_LEFT, HID_KEY_ALT_LEFT, HID_KEY_L},
    {HID_KEY_G, HID_KEY_R, HID_KEY_E, HID_KEY_A, HID_KEY_T}};